apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  volumes:
  - name: pv-volume
    persistentvolumeClaim:
      claimName: pv-claim  
  containers:
    - name: my-container
      image: nginx
      ports:
        - containerPort: 80 
      volumeMount:
      - name: pv-storage
        mountPath: /var/www/html